services:
  - type: web
    name: local-retail-pos-saas
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
